services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    volumes:
      - ./models:/models
    ports:
      - "11434:11434"
    restart: unless-stopped
